### ISSUE TITLE
mojang.com status not displayed properly

### ISSUE THREAD

**Issue by elifoster** [harry2258/AlfredV2-FTB-IRC-#10]
`Minecraft: ✓ | Legacy session: ✓ | Account: ✓ | Auth: ✓ | Skins: ✓ | Auth server: ✓ | Session server: ✓ | Api: ✓ | Textures: ✓: ✓ | `

That last check mark should be prefixed with "Mojang: ".

Additionally, there is a pipe character at the end for no reason.

**Comment by harry2258** [comment]
https://github.com/harry2258/AlfredV2-FTB-IRC-/commit/2b781517d0dbd2b3cbae0887677f95dbdaf1cefe
